### PR TITLE
[XWalk-Extension] add script for usecase-extension-android-tests to a…

### PR DESCRIPTION
**Pull request by jacky-young**
…uto build script pack.py

-Add a auto build script and merged to pack.py->build_extension.py
-Reorganize the usecase-extension-android.tests project

Impacted tests(approved): new 7, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 7, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-5786

### CODE REVIEW

**Comment by jacky-young** [comment]
@jennycao @Shao-Feng please help to review. And @haoyunfeix @qiuzhong please help to review script part. Thanks a lot.

**Comment by haoyunfeix** [comment]
It's OK on pack.py script part.

**Comment by jennycao** [comment]
LGTM

**Comment by qiuzhong** [comment]
build_extension.py part is not OK, @jacky-young , please make a update as we discussed.

**Pull request merged**
