### PR TITLE
[usecase] Change CSP test to manual

### PR DESCRIPTION
**Pull request by haoxli**
Impacted tests(approved): new 0, update 1, delete 0
Unit test platform: Crosswalk Project for Android 17.45.424.0
Unit test result summary: pass 1, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-4600

### CODE REVIEW

**Comment by zqzhang** [comment]
Why change back to manual? Only for PASS?

CC @Honry

**Comment by haoxli** [comment]
CSP need use local server, we need to install docroot.zip to tinyweb.

**Comment by Honry** [comment]
Can we make this as precondition?

**Comment by haoxli** [comment]
It's ok for precondition, i also add it to precondition, but still need to setup precondition by manual.

**Comment by zqzhang** [comment]
Merge as-is.

**Pull request merged**
