### PR TITLE
[wrt] Add wrt-packagemgt test suite for Ostro IoT platform

### PR DESCRIPTION
**Pull request by qiuzhong**
Add a test suite for building Ostro XT image with Crosswalk.
Impacted tests(approved): new 1, update 0, delete 0
Unit test result summary: pass 1, fail 0, block 0

### CODE REVIEW

**Comment by qiuzhong** [comment]
@Honry

**Comment by Honry** [comment]
Pls. fix lint error.

**Comment by qiuzhong** [comment]
Lint errors fixed.

**Comment by Honry** [comment]
LGTM, please cherry-pick to Crosswalk>20 branch.

**Pull request merged**
