### PR TITLE
[webapi] Update Presentation API tests

### PR DESCRIPTION
**Pull request by chunywang**
These tests are followed specification: https://w3c.github.io/presentation-api/
(Presentation API W3C Editor's Draft 22 December 2015)

Impacted TCs num(approved): New 27, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 19.48.485.0
Unit test result summary: Pass 11, Fail 7, Blocked 9

BUG=https://crosswalk-project.org/jira/browse/XWALK-5686

### CODE REVIEW

**Comment by zqzhang** [comment]
@chunywang could you please provide testing results based on latest Crosswalk Project library? Thanks.

**Comment by chunywang** [comment]
Result for  Presentation API cases on Crosswalk for Android(19.48.485.0 ), 
(Pre-Condition: Turn on Settings -> Developer options -> Simulate secondary displays)
1. PresentationRequest.getAvailability() can work
2. PresentationAvailability.value are always false, so onchange eventhandler can't be fired
3. PresentationRequest.start(), reconnect() throw an InvalidAccessError exception

**Comment by chunywang** [comment]
Please don't merge the PR as there are some case errors. i will update the cases as soon as possible

**Comment by zqzhang** [comment]
> (Pre-Condition: Turn on Settings -> Developer options -> Simulate secondary displays)

This shall be documented in REAMDE.md file.

**Pull request merged**
