### PR TITLE
[WebAPI] TC dev for AudioParams nominal range for Chromium 52

### PR DESCRIPTION
**Pull request by renchenglei**
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: Crosswalk for Android 22.52.557.0
Unit test result summary: pass 0, fail 1, block 0

https://crosswalk-project.org/jira/browse/CTS-1862

### CODE REVIEW

**Comment by renchenglei** [comment]
@Honry PTAL, Thanks a lot!

**Comment by Honry** [comment]
Do you have the failure reason?

**Comment by renchenglei** [comment]
@Honry The upstream also has the same error. :)

**Comment by Honry** [comment]
Is there a upstream bug?

**Comment by renchenglei** [comment]
@Honry Maybe it is influenced by the device. I will double check the fail.

**Pull request closed without merging**
