### PR TITLE
[wrt] Remove unnecessary configure files

### PR DESCRIPTION
**Pull request by yunxiaoxie**
- For android only, remove "config.xml,inst.wgt.py,inst.xpk.py" and update suite.json to keep android configure only.
 - For tizen only, remove "manifest.json,inst.apk.py" and update suite.json to keep tizen configure only.

### CODE REVIEW

**Comment by yunxiaoxie** [comment]
Please do not merge this PR, we need manifest.json for xpk, I will update soon.

**Comment by ibelem** [comment]
@yunxiaoxie Besides the manifest.json for xpk update, please also resolve the conflict issue.

**Comment by zqzhang** [comment]
@ibelem @haoxli since @yunxiaoxie has left, will you still need this cleanup? If yes, I prefer to open a new PR and close this one. OK?

**Comment by ibelem** [comment]
@zqzhang I suggest creating a new one.

**Pull request closed without merging**
