### PR TITLE
[stability-embeddingapi] Add image, video, game, multi tab and long time cases for stability

### PR DESCRIPTION
**Pull request by zhuyongyong**
- Repeat 50 times to create 5 views and exit
- Long time playing video
- Long time playing game
- Long time navigation website
- Long time swype up and down website
- Create multi views to load popular website
- Create multi views to load webpages with image contents
- Create multi views to load webpages to load webpages with playing video
- Create multi tab views to load webpages with image contents
- Create multi tab views to load webpages to load webpages with playing video

BUG=https://crosswalk-project.org/jira/browse/XWALK-3783

### CODE REVIEW

**Comment by zqzhang** [comment]
@cicili @zhuyongyong I would like to bring in the Python scripts formatting at #2257, which may affect this PR.

Could you please help review this PR first to avoid duplicate work? Thanks.

**Comment by zqzhang** [comment]
Please remove `[XWALK-3783] ` prefix from commit message.

**Comment by zhuyongyong** [comment]
@zqzhang I've reviewed it, it won't effect the function.

**Comment by jennycao** [comment]
Merge the PR first
@zhuyongyong will create another PR for enhancement

**Pull request merged**
