### PR TITLE
[usecase] Update external URL cases

### PR DESCRIPTION
**Pull request by yinhaichao**
Impacted tests(approved): new 1, update 2, delete 0
Unit test platform: [Linux]
Unit test result summary: pass 1, fail 2, block 0

Fail reason:
 - The external URL will not open in browser but in app window itself

Bug id: xwalk-3898

### CODE REVIEW

**Comment by ibelem** [comment]
@yinhaichao 
usecase/usecase-wrt-linux-tests/res/testapp/org.runtime.externaldynamicurl/manifest.json 

It's better to use hosts part only in xwalk_hosts section, I don't think users will add parameters and values in it.
https://crosswalk-project.org/documentation/manifest/xwalk_hosts.html

**Comment by ibelem** [comment]
@yinhaichao please update the UT result on latest deb build.

**Comment by ibelem** [comment]
@yinhaichao @haoxli any updates for this? I mean the new UT result.

**Comment by ibelem** [comment]
@yinhaichao @haoxli 

+	"xwalk_hosts": [
+			"http://www.baidu.com",
+			"https://www.tenpay.com/v2/index.shtml"
+	],

==>

+	"xwalk_hosts": [
+			"http://www.baidu.com/",
+			"https://www.tenpay.com/"
+	],

**Comment by zqzhang** [comment]
Merge as-is for further development.

**Pull request merged**
