### PR TITLE
[tools] Upload script to separate files per license

### PR DESCRIPTION
**Pull request by zqzhang**
Many thanks to @pjckcs for creating this script.

### CODE REVIEW

**Comment by zqzhang** [comment]
@jennycao I would like to bring in this script as-is and then update it accordingly. What do you think?

**Comment by zqzhang** [comment]
There is a license identification tool for Source Code named Ninka, written in Perl. Perhaps we can try it to identify the source files in this repository.

Usage:
```sh
# How do I use it?
ninka.pl <filename>

# How do I scan files in an entire package? Use xargs. For example, to scan all the files in a directory (and its children) use: 
find * | xargs -n1 -I@ ninka.pl '@'
```

See also
- http://ninka.turingmachine.org/
- https://github.com/dmgerman/ninka
- http://ninka.turingmachine.org/download/ninka-latest-version.tar.bz2

**Comment by zqzhang** [comment]
Found one issue against this tool that it cannot correctly handle files with space in file names. Filed a bug at https://crosswalk-project.org/jira/browse/XWALK-6104

**Comment by jennycao** [comment]
merge this script first for further improvement

**Pull request merged**
