### PR TITLE
[wrt][xwalk-3536] Update get user dynamically for packtool/manifest

### PR DESCRIPTION
**Pull request by yinhaichao**
Impacted tests(approved): new 0, update 266, delete 0
Unit test platform: [Tizen]
Unit test result summary: pass 266, fail 0, block 0

Task: xwalk-3536

### CODE REVIEW

**Comment by ibelem** [comment]
LGTM

**Comment by ibelem** [comment]
@yinhaichao Have you updated readme in test suites for getting tizen user?

**Comment by yinhaichao** [comment]
@ibelem I have not update the readme file, i will do it if the update operate is needed.

**Comment by zqzhang** [comment]
@ibelem can this pull request be landed? It is for multi-users.

**Comment by ibelem** [comment]
LGTM

**Pull request merged**
