### PR TITLE
[wrt][xwalk-3376] Add launch app repeatedly test for wrt

### PR DESCRIPTION
**Pull request by yinhaichao**
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: [Tizen]
Unit test result summary: pass 0, fail 1, block 0

Task: xwalk-3376  Bug: xwalk-3368

### CODE REVIEW

**Comment by ibelem** [comment]
@yinhaichao please make sure if the jQuery.js, testharness.js/css etc. are required in this case? Or please remove them.

**Comment by yinhaichao** [comment]
@ibelem I had checked the case, and removed some unused code

**Comment by ibelem** [comment]
LGTM

**Comment by ibelem** [comment]
@yinhaichao Please resove the conflicts of code.

**Comment by yinhaichao** [comment]
@ibelem I had resove the conflicts of code, please check it. 
Thanks

**Pull request merged**
