### PR TITLE
Add multiple suites for linux platform

### PR DESCRIPTION
**Pull request by yinhaichao**
usecase-wrt-linux-tests
 - Add cases for Update without remove old data
 - Add cases for Open external URL (dynamic/static)
 - Add cases for flash plugin load and display
 - Add cases for csp

wrt-apptools-linux-tests
 - Add pyunit cases for create,pkgName,build

wrt-webappmanu-linux-tests
 - Add web sample apps and hosted apps

### CODE REVIEW

**Comment by ibelem** [comment]
@yinhaichao Please update wrt-webappmanu-linux-tests ==> webappmanu-linux-tests in crosswalk-test-suite/tree/master/misc folder.

**Comment by ibelem** [comment]
Please add unit test results for 

usecase-wrt-linux-tests
wrt-apptools-linux-tests

**Comment by Honry** [comment]
There are 1036 changed files from more than one test suite in on PR, it's really too difficult to review. Better to separate them into one PR one test suite. 
And please move wrt/wrt-apptools-linux-tests to apptools/apptools-linux-tests

**Comment by yinhaichao** [comment]
I will separate test suites into separate PRs, so close it

**Pull request closed without merging**
