### PR TITLE
[usecase-wrt] Guarantee subapp VideoPlay WRITE_EXTERNAL_STORAGE permi…

### PR DESCRIPTION
**Pull request by qiuzhong**
…ssion

VideoPlay requires to access external storage, so guarantee the
WRITE_EXTERNAL_STORAGE permission for the this app.

BUG=https://crosswalk-project.org/jira/browse/XWALK-6062

### CODE REVIEW

**Comment by qiuzhong** [comment]
@Honry

**Comment by qiuzhong** [comment]
@Honry

**Comment by Honry** [comment]
Thank you for capturing this, could you provide the UT result?

**Comment by qiuzhong** [comment]
Impacted tests(approved): new 0, update 1, delete 0
Unit test platform: Crosswalk Project for android 18.46.459.0
Unit test result summary: pass 1, fail 0, block 0

**Comment by Honry** [comment]
LGTM

**Comment by Honry** [comment]
Please update your commit msg rather add comment in Github.

**Comment by qiuzhong** [comment]
@Honry , UT results updated in the commit message.

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
