### PR TITLE
[webapi] Add sub tests config for all-in-one package

### PR DESCRIPTION
**Pull request by haoxli**
tct-backgrounds-css3-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 564, fail 46, block 0

tct-colors-css3-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 88, fail 25, block 0

tct-extra-html5-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 630, fail 9, block 0

tct-fonts-css3-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 129, fail 7, block 0

tct-sandbox-html5-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 54, fail 5, block 0

tct-svg-html5-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 8, fail 8, block 0

tct-text-css3-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 42, fail 5, block 0

tct-webstorage-w3c-tests
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.44.366.0
Unit test result summary: pass 185, fail 9, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-4043

### CODE REVIEW

**Comment by zqzhang** [comment]
@jennycao is this OK to you?

No UT, @haoxli ?

**Comment by haoxli** [comment]
Verified the sub apps can be packed in all-in-one.

**Comment by zqzhang** [comment]
@Honry are you taking care of BDD tests?

**Comment by Honry** [comment]
Better to run the tests to avoid any resource missing.

**Comment by haoxli** [comment]
@jennycao  @Honry We does not support to run BDD tests in all-in-one package, my fix PR just add sub app to all-in-one package, but it still cannot run successfully, there are some special config for them which [~yunfei] use his own workaround. We need have a talk how to pack BDD resources in all-in-one package.

**Comment by Honry** [comment]
I am curious why BDD cannot run in all-in-one?

**Comment by zqzhang** [comment]
> there are some special config for them which @haoyunfeix use his own workaround.

What is the workaround? And why?

**Comment by haoxli** [comment]
@zqzhang  The workaround is copy bdd resources by manual when packing, i will update the PR to pack them automatically.

**Comment by haoxli** [comment]
Please waiting for UT

**Comment by Honry** [comment]
Thanks, @haoxli  LGTM

**Pull request merged**
