### PR TITLE
[ATIP-android] Modify common steps logic

### PR DESCRIPTION
**Pull request by jacky-young**
-Modify common steps logic
-Cover wifi, airplane mode, gps steps
-Back to previous state after operation

BUG=https://crosswalk-project.org/jira/browse/XWALK-4881

### CODE REVIEW

**Comment by jacky-young** [comment]
verified on memo8, zte and nexus 7, @Honry please help to review it.

**Comment by Honry** [comment]
@jacky-young, does this PR fix https://crosswalk-project.org/jira/browse/XWALK-4881?
@JianfengXu, please help to land this patch locally to verify your https://github.com/crosswalk-project/crosswalk-test-suite/pull/2737

**Comment by jacky-young** [comment]
yes, of course it will fix 4881.

**Comment by Honry** [comment]
Please reference the link in your summary.

**Comment by jacky-young** [comment]
Add nexus5 device support.

**Comment by Honry** [comment]
what about Nexus 4?

**Comment by jacky-young** [comment]
add nexus5 device support

**Comment by kangxu** [comment]
Verify tests added in https://github.com/crosswalk-project/crosswalk-test-suite/pull/2766 and https://github.com/crosswalk-project/crosswalk-test-suite/pull/2768 with update in this PR on memo platform, tests got pass

**Comment by Honry** [comment]
Thank you all for the support, LGTM

**Pull request merged**
