### PR TITLE
[apptools-android] Add case to test automatic conversion of assets for apptools android

### PR DESCRIPTION
**Pull request by yunxliu**
Failure analysis:
https://crosswalk-project.org/jira/browse/XWALK-5049

Impacted tests(approved): new 12, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 4, fail 8, block 0

https://crosswalk-project.org/jira/browse/XWALK-3829

### CODE REVIEW

**Comment by Honry** [comment]
I don't approve this test since we still have no idea on the usage of this new feature.

**Comment by yunxliu** [comment]
I will update this pr when this new feature has implement.

**Comment by Honry** [comment]
Hold on this PR, test case may need update after XWALK-5049 got resolved.

**Comment by Honry** [comment]
LGTM

**Pull request merged**
