### PR TITLE
[Windows] Combine pack_windows.py to pack.py

### PR DESCRIPTION
**Pull request by zhuyongyong**
- It is fine to pack msi pkg

BUG=https://crosswalk-project.org/jira/browse/XWALK-6065

### CODE REVIEW

**Comment by jennycao** [comment]
@qiuzhong @haoyunfeix Pls also help to review this PR

**Comment by haoyunfeix** [comment]
LGTM

**Comment by qiuzhong** [comment]
I tried this PR and it worked fine.
pack.py now supports msi package.

**Comment by jennycao** [comment]
LGTM

**Pull request merged**
