### PR TITLE
[atip-linux] Enable deepin app launch/initial function in ATIP

### PR DESCRIPTION
**Pull request by kangxu**
Enable deepin app launch/initial function in ATIP refer to the comments
in XWALK-4721

### CODE REVIEW

**Comment by Honry** [comment]
Please provide the Dry Run result for both android and deepin tests.

**Comment by kangxu** [comment]
@Honry  Try run deepin automation tests added in https://github.com/crosswalk-project/crosswalk-test-suite/pull/2837 and android automation tests of tct-notification-w3c-tests, tests got pass.

**Comment by Honry** [comment]
Thanks, LGTM

**Comment by Honry** [comment]
And please also add relative update for Deepin support in atip/README.md.

**Pull request merged**
