### PR TITLE
[Embeddingapi] Use diff package name for embedding-api-android-tests …

### PR DESCRIPTION
**Pull request by zhuyongyong**
…and embedding-asyncapi-android-tests

BUG=https://crosswalk-project.org/jira/browse/CTS-1772

### CODE REVIEW

**Comment by Shao-Feng** [comment]
Pls also update the 'inst.py' for install and uninstall this packages, alsowise this change will break inst.py

**Comment by zhuyongyong** [comment]
@Shao-Feng  you can refer to the file "inst.apk.py" for the update change.

**Comment by Shao-Feng** [comment]
do you mean the inst.apk.py will be rename as inst.py in the generated zip file?

**Comment by zhuyongyong** [comment]
Yes

**Pull request merged**
