### PR TITLE
[EmbeddingApi] Add usecase to achive disabling copy/paste toolbar in …

### PR DESCRIPTION
**Pull request by jacky-young**
…XWalkView

-Add usecase to achive disabling copy/paste toolbar in XWalkView
-Cover the XWalkActivity and XWalkInitializer two ways

Impacted tests(approved): new 2, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 2, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-4789

### CODE REVIEW

**Comment by jacky-young** [comment]
@jennycao please help to review it.

**Comment by jennycao** [comment]
@Shao-Feng Yunlong add the usecase of  OnLongClickListener, 
which is in our extended test dev plan, pls also help to review :)

**Comment by jennycao** [comment]
@jacky-young Pls solve the conflict

**Comment by Shao-Feng** [comment]
It looks good to me

**Comment by jacky-young** [comment]
@jennycao it is ok now.

**Pull request merged**
