### PR TITLE
[webapi] Add "extension" parameter for Teskitlite in realsense test suite

### PR DESCRIPTION
**Pull request by chunywang**
- Update latest realsense_extensions link
- Add "extension" parameter for Teskitlite

https://crosswalk-project.org/jira/browse/XWALK-6595

### CODE REVIEW

**Comment by zqzhang** [comment]
@Shao-Feng is this OK to you?

**Comment by Shao-Feng** [comment]
Jenny just show me a manifest.json. https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/usecase/usecase-apptools-tests/testapp/manifestextension/manifest.json
in the last line, 

"xwalk_extensions": ["extension/echo_extension", "extension/echo_extension_bridge"]

could you try if realsence suite could also define the extension in manifest like above?
If yes, we can re-base testkit-lite and remove this features.

**Comment by Shao-Feng** [comment]
Whatever the "xwalk_extensions" in manifest work or not, the suite name should be corrected.

**Comment by chunywang** [comment]
@Shao-Feng at present, https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/webapi/webapi-realsense-xwalk-tests/manifest.json has added "xwalk_extensions"

**Comment by chunywang** [comment]
I will try it and give the result later.

**Comment by Shao-Feng** [comment]
OK, then, it seems APP-tool can't deal with the manifest without the parameter. if so, this patch looks OK to me

**Comment by chunywang** [comment]
I tried  "xwalk_extensions" in manifest and extension="xwalk-extensions" in xml with testkit-lite, it can run at first, then get a xwalk.exe error and black screen.

**Comment by BruceDai** [comment]
I tested the package with this PR on HP Spectre x2 (Windows 10) by latest testkit-lite(https://github.com/testkit/testkit-lite/releases/download/lite-3.1.17-3/testkit-lite_3.1.17_all.deb), result is : total 157 pass 110 fail 5 block 42. these two cases enhanced_photography and face both have some block for "Uncaught Error: assert_unreached: Access to audio and video stream get error: Reached unreachable code".

**Comment by chunywang** [comment]
I tested with testkit-lite 3.1.16, i will try with 3.1.17 again.

**Pull request merged**
