### PR TITLE
 [usecase-embedding] Add a use case for dispatchDraw

### PR DESCRIPTION
**Pull request by Shao-Feng**
Signed-off-by: Shaofeng <shaofeng.tang@intel.com>

 [usecase-embedding] Add a usecase for dispatchDraw(Canvas canvas)

Impacted tests(approved): new 2, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 2, fail 0, block 0

### CODE REVIEW

**Comment by jennycao** [comment]
Pls  add a category prefix [usecase-embedding] in the summary

**Comment by Shao-Feng** [comment]
updated

**Comment by zqzhang** [comment]
> Signed-off-by: Shaofeng shaofeng.tang@intel.com

@Shao-Feng we don't use signed-off (-s) when submit PR to this project, though it is not a big issue.

**Comment by zqzhang** [comment]
Another just a reminder, we don't use tab for indentation in this project for new tests. For Java, `4 spaces, no tab` following http://google-styleguide.googlecode.com/svn/trunk/javaguide.html, see `doc/Coding_Style_Guide_CheatSheet.md`.

**Comment by Shao-Feng** [comment]
2 new commits are added

**Comment by jennycao** [comment]
LGTM

**Pull request merged**
