### PR TITLE
[webapi] Add test to check device type by window.location.search

### PR DESCRIPTION
**Pull request by chunywang**
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: Crosswalk Project for Android 15.43.353.0
Unit test result summary: pass 0, fail 1, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-4325

### CODE REVIEW

**Comment by chunywang** [comment]
Please don't merge the pr before https://crosswalk-project.org/jira/browse/XWALK-4318 is resolved.

**Comment by zqzhang** [comment]
Hmm, this may be related to `navigator.userAgent`, which is also tested in #2350. Please continue to follow XWALK-4318.

**Comment by chunywang** [comment]
I will improve the case, and submit it to w3c

**Comment by zqzhang** [comment]
Just close this.

**Pull request closed without merging**
