### PR TITLE
[misc] Rename suite and tests name for Sampleapp-tizen

### PR DESCRIPTION
**Pull request by yunxiaoxie**
- Remove wrt- from sampleapp suite name
 - Remove Crosswalk_SampleAPP_ from filenames
 - Update configure files
 - Sample apps can also be used for API testing

### CODE REVIEW

**Comment by zqzhang** [comment]
grep 'wrt-sampleapp-tizen-tests' -r *
doc/Web_Test_Suite_Packaging_Guide.md:- wrt-sampleapp-tizen-tests

**Comment by zqzhang** [comment]
> The suite is not only for wrt, so remove them

Not accurate. Sample apps can also be used fro API testing.

**Comment by yunxiaoxie** [comment]
Updated Web_Test_Suite_Packaging_Guide.md in PR1673.

**Comment by jennycao** [comment]
@ibelem @cicili Pls help to review and confirm this change :)

**Pull request merged**
