### PR TITLE
[usecase] Add new baseline data for usecase-webapi-xwalk-tests on Nexus9 and ECS2-8A

### PR DESCRIPTION
**Pull request by kangxu**
https://crosswalk-project.org/jira/browse/XWALK-5559

### CODE REVIEW

**Comment by kangxu** [comment]
Update in this PR rely on https://github.com/crosswalk-project/crosswalk-test-suite/pull/3136. UT result will be added after related PR merged and pack script issue of apptools is fixed

**Comment by Honry** [comment]
You can use app-tools v0.8 which is a stable version to build 64bit package.

**Comment by Honry** [comment]
@kangxu, please provide the UT result.

**Comment by ibelem** [comment]
@kangxu, please provide the UT result.

**Comment by kangxu** [comment]
Close this PR and commit update again

**Pull request closed without merging**
