### PR TITLE
[webapi][XWALK-3022] Update location port test from w3c

### PR DESCRIPTION
**Pull request by xinliux**
- Keep location port test same with w3c.

Impacted tests(approved): new 0, update 1, delete 0
Unit test platform: [IVI] crosswalk-11.40.277, t-e-c 0.135
Unit test result summary: pass 1, fail 0, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
Hmm, this is a test from https://github.com/w3c/web-platform-tests/blob/master/old-tests/submission/Infraware/Session_History/contents/Session_History/location_port.html

Can we take some efforts to move these tests into proper place and make bug-fixing then?

**Comment by xinliux** [comment]
OK, When I update these case, should I add the link author  from intel ?

**Comment by xinliux** [comment]
@zqzhang  
https://github.com/w3c/web-platform-tests/pull/1599

The PR have been merged, Please merge this PR to fix the bug issue, I will create new PR to update other sessionhistory tests from w3c.

**Comment by zqzhang** [comment]
@xinliux thanks. But you give me a wrong link. It is https://github.com/w3c/web-platform-tests/pull/1597

**Pull request merged**
