### PR TITLE
[webapi][XWALK-3323] Fix improper tct-package-tizen-tests input values

### PR DESCRIPTION
**Pull request by sstolinski**
This patch fixes improper values in conversion table
which are used to validate conversion.

### CODE REVIEW

**Comment by zqzhang** [comment]
Literally, I think, this update looks good.

However, I would expect an unique unitcommon.js in all test suite.

I will talk to Samsung Web TCT to see if they want this change. Stay tune.

**Comment by sstolinski** [comment]
@zqzhang I need this patch to fix https://crosswalk-project.org/jira/browse/XWALK-3248.
If it is possible please merge it. If unitcommon.js should be changed/moved/etc. I change it in next commit.

**Comment by tiwanek** [comment]
I'm not sure if this is testsuite fault:
http://www.w3.org/TR/WebIDL/#TreatUndefinedAs
http://www.w3.org/TR/WebIDL/#dfn-optional-argument

**Comment by tiwanek** [comment]
Check: 
https://lists.w3.org/Archives/Public/public-script-coord/2015JanMar/0012.html

Please, rework this to described behaviour (null value case).

**Comment by zqzhang** [comment]
@tiwanek @sstolinski if I read the thread correctly, passing `undefined` as optional nullable param shall not throw. And that is why we need to rework here.

**Comment by tiwanek** [comment]
@zqzhang 
I understand it same way.

@sstolinski 
What about cases "enum" and "double"?

**Comment by sstolinski** [comment]
@tiwanek  Done

**Comment by tiwanek** [comment]
Thanks. For me, it looks good.

**Comment by zqzhang** [comment]
Many thanks.

**Comment by zqzhang** [comment]
@sstolinski feel free to update all `unitcommon.js` files.

BTW, I have been thinking of maintaining only one copy of such file at #875; is that better?

**Comment by zqzhang** [comment]
This has been applied to IVI TCT, thanks.

**Comment by sstolinski** [comment]
I will update all unitcommon.js.

 

IMHO it is good idea.

But some the files are not copies – there are approximately 4-5 different versions (some of them easy to merge).

So at the result 2-3 versions of unitcommon.js will be exists.

 

cid:image001.png@01CE8F77.458ECDF0

 

Sebastian Stoliński

Samsung R&D Institute Poland

Samsung Electronics

 <mailto:s.stolinski@samsung.com> s.stolinski@samsung.com

**Pull request merged**
