### PR TITLE
[misc] Rename suite and tests name for Sampleapp-android

### PR DESCRIPTION
**Pull request by yunxiaoxie**
- Remove wrt- from sampleapp suite name
 - Remove Crosswalk_SampleAPP_ from filenames
 - Update configure files
 - Sample apps can also be used for API testing

### CODE REVIEW

**Comment by jennycao** [comment]
@cicili pls also review this PR

**Comment by zqzhang** [comment]
grep 'wrt-sampleapp-android-tests' -r *
doc/Web_Test_Suite_Packaging_Guide.md:- wrt-sampleapp-android-tests

**Comment by zqzhang** [comment]
> The suite is not only for wrt, so remove them

Not accurate. Sample apps can also be used fro API testing.

**Comment by jennycao** [comment]
@ibelem Pls help to review and confirm this change :)

**Comment by jennycao** [comment]
I am not sure why remove Crosswalk_SampleApp_ prefix in the testcase name and test case html file

**Pull request merged**
