### PR TITLE
[pack-script] Add pack support for 64bits

### PR DESCRIPTION
**Pull request by haoyunfeix**
1. Add x86_64 and arm64 options
2. Change service all-in-one packing path

### CODE REVIEW

**Comment by Honry** [comment]
@haoyunfeix, please provide the UT result.

**Comment by haoyunfeix** [comment]
webapi service all-in-one package can build successfully.
I compared the tests.xml with branch Crosswalk-17's, they'are the same.

**Comment by Honry** [comment]
LGTM

**Comment by jennycao** [comment]
LGTM

**Comment by jennycao** [comment]
@haoyunfeix Pls also submit to Crosswalk 16

**Pull request merged**
