### PR TITLE
[usecase-wrt] Add test for 64bit Crosswalk APK support in Play Store

### PR DESCRIPTION
**Pull request by haoxli**
Impacted tests(approved): new 1, update 1, delete 0
Unit test platform: Crosswalk for Android 19.49.514.4
Unit test result summary: pass 2, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/CTS-611

### CODE REVIEW

**Comment by haoxli** [comment]
@Honry

**Comment by haoxli** [comment]
@yhe39

**Comment by yhe39** [comment]
LGTM

**Comment by Honry** [comment]
@haoxli, you should also cherry-pick to Crosswalk-19 and Crosswalk-20.

**Pull request merged**
