### PR TITLE
[webapi][XWALK-2599/3770] Add extension/KHR_gl_sharing tests for WebCL

### PR DESCRIPTION
**Pull request by chunywang**
Impacted tests(approved): new 2, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 0, fail 2, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
Is there any test from https://github.com/KhronosGroup/WebCL-conformance checking this?

**Comment by zqzhang** [comment]
And feedback for my question above, @chunywang ?

**Comment by chunywang** [comment]
yes, KhronosGroup has test cases to check webcl extension and  KHR_gl_sharing extension

**Comment by zqzhang** [comment]
Which one(s)? Shall we close this PR?

**Comment by chunywang** [comment]
This PR is covered by https://github.com/KhronosGroup/WebCL-conformance/blob/master/conformance/extension/ , there are tests testing extension on KHR_gl_sharing, KHR_fp16, KHR_fp64, WEBCL_html_image, WEBCL_html_video.
KHR_gl_sharing test is covered by https://github.com/KhronosGroup/WebCL-conformance/blob/master/conformance/extension/KHR_gl_sharing/functionalityTesting/bufferFromGLBuffer.html

**Pull request closed without merging**
