### PR TITLE
[webapi] Sync WebStorage upstream tests

### PR DESCRIPTION
**Pull request by chunywang**
Impacted tests(approved): new 4, update 23, delete 1
Unit test platform: Crosswalk Project for Android 19.49.508.0
Unit test result summary: pass 134, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-6729
BUG=https://crosswalk-project.org/jira/browse/XWALK-4595

### CODE REVIEW

**Comment by Honry** [comment]
Any reason for the failures?

**Comment by chunywang** [comment]
These failure and block tests need server.

**Comment by Honry** [comment]
We have a tinyweb service, only need to set ```"hosted-app": "true"``` in suite.json, see [ tct-xmlhttprequest-w3c-tests](https://github.com/crosswalk-project/crosswalk-test-suite/tree/master/webapi/tct-xmlhttprequest-w3c-tests ) for instance, or you can ask @haoxli for help.

**Comment by chunywang** [comment]
but webstorage test suite also have bdd cases, if i add the test suite into all-in-one, it can't run.

**Comment by chunywang** [comment]
@Honry , webstorage test suite has been added into allinone list, and the bdd cases also can run. please review!

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
