### PR TITLE
[usecase-extension] Clean up residuary make_apk.py dependent tests

### PR DESCRIPTION
**Pull request by haoxli**
https://crosswalk-project.org/jira/browse/XWALK-6148

### CODE REVIEW

**Comment by haoxli** [comment]
@jacky-young please help to review this PR, thanks.

**Comment by Honry** [comment]
Let's hold on this PR until https://github.com/crosswalk-project/crosswalk-app-tools/pull/85 is merged which is a fix for external extension build with app-tools.

**Comment by jacky-young** [comment]
@haoxli This PR crosswalk-project/crosswalk-app-tools#85 may adjust external extension building file structure. So usecase-extension-android-tests/README.md will be a little different. BTW, crosswalk-pkg should have no this argument '--enable-remote-debugging'.

**Comment by haoxli** [comment]
'--enable-remote-debugging' is supported by app tools. @jacky-young If you have your own update plan, you can submit your PR, and link to this one, I will close mine.

**Comment by Honry** [comment]
@haoxli, please verify this PR with latest app-tools.

**Comment by Honry** [comment]
'--enable-remote-debugging' is default, there's no such command line in app-tools.

**Comment by jacky-young** [comment]
@haoxli I have updated these two file on https://github.com/crosswalk-project/crosswalk-test-suite/pull/3303, you can close this now.

**Comment by haoxli** [comment]
thanks

**Pull request closed without merging**
