### PR TITLE
[usecase-extension] Clean up residuary make_apk.py dependent tests

### PR DESCRIPTION
**Pull request by jacky-young**
https://crosswalk-project.org/jira/browse/XWALK-6148

### CODE REVIEW

**Comment by jacky-young** [comment]
@Honry please help to review.

**Comment by Honry** [comment]
Please provide the UT result.

**Comment by jacky-young** [comment]
update UT test result:
Impacted tests(approved): new 0, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 7, fail 0, block 0

**Comment by Honry** [comment]
Please add the UT to your commit message.

**Comment by Honry** [comment]
LGTM

**Pull request merged**
