### PR TITLE
WifiDirect Experimental API use case manual test

### PR DESCRIPTION
**Pull request by astojilj**
Depends on another pull request: https://github.com/crosswalk-project/crosswalk/pull/3327
@jondong, could you please help on reviewing this one too? Thanks.

### CODE REVIEW

**Comment by astojilj** [comment]
@jondong, updated the commit according to your comments. Thanks.

**Comment by astojilj** [comment]
@rakuco: @jondong already LGTM-ed it here, https://github.com/astojilj/crosswalk-test-suite/commit/461a84deb5b90484ad0d5887f117c8d44727bbad#commitcomment-14147243
"
jondong  commented on 461a84d 7 days ago  
LGTM with some style nits. Thanks for the patch!
"
Maybe you could also check and integrate? thanks

**Comment by astojilj** [comment]
@jennycao @ibelem could you, please, check this one now that the API got integrated - https://github.com/crosswalk-project/crosswalk/pull/3359 ? Thanks.

**Comment by zqzhang** [comment]
Thank you very much for the pull request, is there a JIRA feature requirement against the WifiDirect support? If not, please help file one. QA needs to do feature verification using this use-case test, thanks.

I am sorry for late response because lost of tracking GitHub notification.

@chunywang could you please help check the PR with 17.45.433.0? Thanks.

**Comment by chunywang** [comment]
OK

**Comment by astojilj** [comment]
@zqzhang Thanks. API wasn't submitted until yesterday, so good you didn't waste time.
> is there a JIRA feature requirement against the WifiDirect support?
Only few lines in XWALK-5158. I will add there some more information.

**Comment by zqzhang** [comment]
Thanks, merging.

https://crosswalk-project.org/jira/browse/XWALK-5158

**Comment by astojilj** [comment]
@zqzhang @chunywang Thanks.

**Pull request merged**
