### PR TITLE
[Stability-Embeddingapi] Add code to implement interplay between the …

### PR DESCRIPTION
**Pull request by jacky-young**
…python and java for auto cases

- Add code to implement interplay between the python and java for auto stability cases
- Connected with /mnt/sdcard/file

BUG=https://crosswalk-project.org/jira/browse/XWALK-4277

### CODE REVIEW

**Comment by jacky-young** [comment]
@jennycao please help to review it.

**Comment by jennycao** [comment]
LGTM

**Comment by jennycao** [comment]
@zhuyongyong Pls also review :)

**Comment by zhuyongyong** [comment]
LGTM

**Pull request merged**
