### PR TITLE
[EmbeddingApi] Add usecase of WebView for xwalkview reference

### PR DESCRIPTION
**Pull request by jacky-young**
-modify webview usecase WebViewWithLayoutActivity
-add webview usecase WebViewWithAnimatableActivity
-add webview usecase WebViewWithLoadDataWithBaseURL
-add webview usecase WebViewWithMultiInstanceActivity
-add webview usecase WebViewWithPlayVideoActivity
-add webview usecase WebViewWithPauseTimerActivity

Impacted tests(approved): new 5, update 1, delete 0
Unit test platform: [Android]
Unit test result summary: pass 6, fail 0, block 0

https://crosswalk-project.org/jira/browse/XWALK-5057

### CODE REVIEW

**Comment by jacky-young** [comment]
@Shao-Feng please help to review it.

**Comment by Shao-Feng** [comment]
Follow https://crosswalk-project.org/jira/browse/XWALK-5056
to update

**Comment by jacky-young** [comment]
@Shao-Feng please review again.

**Comment by Shao-Feng** [comment]
LGTM

**Pull request merged**
