### PR TITLE
[usecase] Update bootstrap framework to usecase

### PR DESCRIPTION
**Pull request by JianfengXu**
- Mantain bootstrap framework to tools/bootstrap-fw
- Update usecase samples for bootstrap framework
- Update suite.json to copy framework from tools
- Move DownloadAndroid to usecase-webapi-xwalk-tests

### CODE REVIEW

**Comment by zqzhang** [comment]
@jennycao since this pull request will affect all usecase tests development; let's speed up the review process.

2 concerns:
- `usecase-fw` sounds not good; this framework shall be used for all behavior-derived tests suites; how about `uifw`
-  why tools/usecase-fw/fonts/._glyphicons-halflings-regular.eot and other 3 files like this?

**Comment by JianfengXu** [comment]
@zqzhang 
These four files are hidden files, I have removed them.

**Comment by jennycao** [comment]
@JianfengXu @zqzhang let's named the folder as bootstrap-uifw for general usage consideration:)

**Comment by zqzhang** [comment]
Why not `bootstrap` rather than `bootstrap-uifw`?

**Comment by JianfengXu** [comment]
I have updated usecase-fw to bootstrap-fw.

**Pull request merged**
