### PR TITLE
[webapi] Enable MSI package in webapi test suites

### PR DESCRIPTION
**Pull request by haoxli**
BUG=https://crosswalk-project.org/jira/browse/XWALK-5632

### CODE REVIEW

**Comment by haoxli** [comment]
There are about 30 suites fail to build, because the file name is too long.

**Comment by Honry** [comment]
Any failure reason? I am curious why a long name would lead to building fail.
BTW, developer is planing to make the last portion as default app name, related feature is XWALK-5658, I think it would help.

**Comment by haoxli** [comment]
This is about package id length, our build issue is because app tools will create .wxs, it limit the column content length in 72 characters:
```
ICE03: String overflow (greater than length permitted in column); Table: File, Column: Component_, Key(s): opt_tct_3dtransforms_css3_tests_3dtransforms_csswg_css_transform_3d_rotateY_negative_manual.html
```

**Comment by haoxli** [comment]
Report the pack issue in https://crosswalk-project.org/jira/browse/XWALK-5679

**Comment by haoxli** [comment]
UT in https://crosswalk-project.org/jira/browse/XWALK-5632

**Comment by jennycao** [comment]
LGTM

**Pull request merged**
