### PR TITLE
Add CSS Device Adaptation test suite to testing scope

### PR DESCRIPTION
**Pull request by zqzhang**
And update spec link and category.

https://crosswalk-project.org/jira/browse/XWALK-577

### CODE REVIEW

**Comment by zqzhang** [comment]
Hi @jennycao @qiuzhong , is this OK to add a test suite to release scope?

**Comment by zqzhang** [comment]
@chunywang seems all the tests are manual, could you please try this test suite on latest Crosswalk Project for Android, and provide results here as comment? Thanks.

**Comment by jennycao** [comment]
@zqzhang I will merge this PR, @qiuzhong Pls be notice that webapi-deviceadaption-w3c-tests suite is added in the test release scope.

**Comment by chunywang** [comment]
@zqzhang  webapi-deviceadaptation-css3-tests tests result:

Impacted TCs num(approved): New 19, Update 0, Delete 0
Unit test Platform: Crosswalk Project for Android 15.44.396.0
Unit test result summary: Pass 2, Fail 17, Blocked 0 

The pass tests id:
zoom_auto
max-zoom_auto

**Comment by zqzhang** [comment]
Thanks, @chunywang. How about Chrome for Android?

**Comment by chunywang** [comment]
@zqzhang I don't know how to run on Chrome for Android, as the http://wts.crosswalk-project.org/runner/index.html
doesn't contain CSS Device Adaptation.

**Comment by zqzhang** [comment]
OK, thanks.

**Pull request merged**
