### PR TITLE
Cherry-pick inst.py improvement from master to Crosswalk-21

### PR DESCRIPTION
**Pull request by qiuzhong**
Update:
1. Use abspath when scp packages
2. Add a new inst.py for docroot on IoT

### CODE REVIEW

**Comment by Honry** [comment]
Why still so many commits?

**Comment by qiuzhong** [comment]
I didn't always create a new branch for submit. My local branch conflicts with the remote branch, I fixed these conflicts. However, all the cherry-pick keep the same content to submit.

**Comment by qiuzhong** [comment]
These commits only happens on my fork repository.

**Comment by Honry** [comment]
You should pull your fork repo to align with upstream repo firstly. Thus these extra commits will go away naturally.

**Comment by qiuzhong** [comment]
Close this PR and submit again after alignning with the upstream repo.

**Pull request closed without merging**
