### PR TITLE
[usecase-cordova] Add WebSQLDatabase testing back for migrating

### PR DESCRIPTION
**Pull request by haoxli**
Impacted tests(approved): new 0, update 1, delete 0
Unit test platform: Crosswalk Project for Android 24.53.593.0
Unit test result summary: pass 1, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-6732

### CODE REVIEW

**Comment by haoxli** [comment]
@zhuyongyong  Do you know why we comment this checkpoint before?

**Comment by zhuyongyong** [comment]
@haoxli  As the feature XWALK-4488 is not resolved before, we comment this checkpoint temporarily.

**Comment by haoxli** [comment]
Move to Crosswalk 21.

**Comment by haoxli** [comment]
Move to feature release

**Comment by haoxli** [comment]
Feature is merged in Crosswalk 23.53.589.3 and 24.53.593.0.

**Comment by Honry** [comment]
Can we merge it now?

**Pull request merged**
