### PR TITLE
[WebAPI] Fix lint error in webgl tests

### PR DESCRIPTION
**Pull request by renchenglei**
- Fix TRAILING WHITESPACE
  sed -i 's/[ \t]*$//' /path/to/file
- Fix INDENT TABS
  sed -i 's/	/ /g' /path/to/file
- Fix CR AT EOL
  sed -i 's/\r/\n/g' /path/to/file

BUG=https://crosswalk-project.org/jira/browse/CTS-1692

### CODE REVIEW

**Comment by renchenglei** [comment]
@zqzhang , @Honry 
 Ptal, thanks a lot!

**Comment by renchenglei** [comment]
@zqzhang , @Honry
Ptal, thanks a lot!

**Comment by Honry** [comment]
Too many files changed in one PR to review, it's better to split it into two by test suite.

**Comment by renchenglei** [comment]
PTAL, thanks a lot~!

**Comment by Honry** [comment]
LGTM

**Pull request merged**
