### PR TITLE
[usecase] Combine CSS style for app version

### PR DESCRIPTION
**Pull request by haoxli**
- Combine two app version style together
- Remove useless css file

### CODE REVIEW

**Comment by zqzhang** [comment]
This sounds like you incorporate some code snippets from 3rd party to our licensed file, right?

**Comment by haoxli** [comment]
Yes, we copy part css from bootstrap, and do some changes and add ours css style

**Comment by zqzhang** [comment]
@haoxli shall we close this now or you rewrite it?

**Comment by zqzhang** [comment]
Close this.

**Pull request closed without merging**
