### PR TITLE
[webapi][XWALK-3363] Add test for CORS DELETE request-type

### PR DESCRIPTION
**Pull request by kangxu**
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: [Android]
Unit test result summary: pass 1, fail 0, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
Is this test qualified for W3C?

**Comment by kangxu** [comment]
@zqzhang 
  Description on cors DELETE request-type are not detailed enough in W3C spec,  I add this test just for covering this issue [XWALK-3363](https://crosswalk-project.org/jira/browse/XWALK-3363). If submitted to w3c, checkpoints are not strict enough and I extractted test point from spec example mainly.

**Comment by zqzhang** [comment]
Better submit to W3C; if not, we don't need such test either.

**Comment by haoxli** [comment]
I check the CORS spec(http://www.w3.org/TR/cors/), i think we don't need the test for DELETE request-type. close it.

**Comment by kangxu** [comment]
No detailed info found in spec, so close PR.

**Pull request closed without merging**
