### PR TITLE
[webapi] Update xml configure files

### PR DESCRIPTION
**Pull request by kangxu**
- Update test entery in xml for tct-forms-html5-tests,
webapi-webcl-nonw3c-tests and webapi-webrtc-w3c-tests

- Remove duplicated test entery in xml for webapi-webcl-nonw3c-tests
and tct-indexeddb-w3c-tests

Impacted suites: tct-forms-html5-tests
Impacted tests(approved): new 0, update 2, delete 0
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 2, fail 0, block 0

Impacted suites: tct-indexeddb-w3c-tests
Impacted tests(approved): new 0, update 0, delete 7
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 0, fail 0, block 0

Impacted suites: webapi-webcl-nonw3c-tests
Impacted tests(approved): new 0, update 1, delete 2
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 0, fail 1, block 0

Impacted suites: webapi-webrtc-w3c-tests
Impacted tests(approved): new 0, update 6, delete 0
Unit test platform: Crosswalk for Android 15.43.354
Unit result summary: pass 6, fail 0, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
Better with 4 commits in this PR.

**Comment by kangxu** [comment]
@zqzhang  I will split this PR into 4 commits

**Comment by kangxu** [comment]
@zqzhang  I have updated it following your comments

**Comment by zqzhang** [comment]
Please update all the commit messages accordingly, thanks.

**Comment by kangxu** [comment]
@zqzhang Conflicts in this PR can't be resolved, so close it. I have updated it following your comments  in another PR https://github.com/crosswalk-project/crosswalk-test-suite/pull/2574

**Pull request closed without merging**
