### PR TITLE
[sampleapp-android] Change make.py to apptools

### PR DESCRIPTION
**Pull request by yunxliu**
Impacted tests(approved):new 0,update 42,delete 0
Unit test platform:[Deepin]
Unit test result summary:pass 42,fail 0,block 0

### CODE REVIEW

**Comment by Honry** [comment]
About the title: should be make_apk.py
And pending this update, since apptools does not support shared mode yet.

**Comment by yunxliu** [comment]
I will update this pr when apptools supports shared mode

**Comment by zqzhang** [comment]
I guess you guys want this to be closed and to make new PR in need, right?

**Comment by Honry** [comment]
Yes, I will close it.

**Pull request closed without merging**
