### PR TITLE
[webapi][XWALK-2955] Modify background color for reftests

### PR DESCRIPTION
**Pull request by chenxix**
Because background color by using png image(support/1x1-green.png) does not match background color of css style.
Impacted tests(approved):new 0,update 17,delete 0
Unit test platform:[TizenIVI]
Unit test result summary:pass 17,fail 0,block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
What I expect is that all changes shall be submitted to W3C firstly!

If you have submitted to W3C and got accept, please use 'Integrate ... from W3C' or 'Update ... to reflect W3C latest'

**Comment by zqzhang** [comment]
And please list the links to W3C files or pull requests in commit message.

**Comment by chenxix** [comment]
This modification I have commit to master before. and now just push to Crosswalk-10 branch.

**Comment by zqzhang** [comment]
Show me that link; and why not submit to W3C?

**Pull request closed without merging**
