### PR TITLE
[webapi][XWALK-3388] Improve sub wgt for Wgt API

### PR DESCRIPTION
**Pull request by kangxu**
- Advance the variable definition to avoid undefined
- Fail Reason: Verified in tizen-common_20150210.3,

Comments: Fail to get the value of widget.preferences attributes, issue tracked by XWALK-3386

Impacted tests(approved): new 0, update 6, delete 0
Unit test platform: [IVI]
Unit test result summary: pass 5, fail 1, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
UT? Please make a short description why make this update.

**Comment by kangxu** [comment]
@zqzhang ， I have updated it following your comments.

**Comment by zqzhang** [comment]
> Fail Reason: Verified in tizen-ivi_20150114.3_ivi-mbr-i586, this image does not contain that fix patch. XWALK-2775

Please wait this issue fixed.

**Comment by kangxu** [comment]
@zqzhang 
I have reverified it in tizen-common_20150210.3, [XWALK-2775](https://crosswalk-project.org/jira/browse/XWALK-2775) issue has been fixed. Failed test tracked by [XWALK-3386](https://crosswalk-project.org/jira/browse/XWALK-3386).Update in this PR has no influence on this issue.

**Comment by zqzhang** [comment]
Merge as-is.

**Pull request merged**
