### PR TITLE
[apptools][ios] Add 3 tests

### PR DESCRIPTION
**Pull request by Honry**
Impacted tests(approved): new 3, update 0, delete 0
  Unit test platform: [iOS]
  Unit test result summary: pass 1, fail 2, block 0

  Fail Reason: XWALK-4048

### CODE REVIEW

**Comment by Honry** [comment]
@ibelem, Could you help review it?

**Comment by ibelem** [comment]
@Honry Will 

"crosswalk-app build debug" work? Any case or step about it? I know "crosswalk-app build" == "crosswalk-app build debug".

**Comment by Honry** [comment]
Test case in https://github.com/crosswalk-project/crosswalk-test-suite/blob/master/apptools/apptools-ios-tests/apptools/build.py, it can be built successfully. But the remote debug has not implemented.

**Comment by ibelem** [comment]
LGTM

**Pull request merged**
