### PR TITLE
[misc] Update sampleapp pack script

### PR DESCRIPTION
**Pull request by haoxli**
- Add 64bit pack script
- Update HexGL code
- Reconstruct code

### CODE REVIEW

**Comment by jennycao** [comment]
@haoxli Could 64bit pack script be merged to sample_app_pack.sh?
@qiuzhong Pls also review and verify this PR

**Comment by haoxli** [comment]
It will make script code more complex if we merge them together. For crosswalk 64bit, it have different layout, we need do special updates for extension_android. Suggest to separate them.

**Comment by qiuzhong** [comment]
For 32bit script, it works well.
For 64bit:
x86 --> x86_64
armeabi-v7a --> arm64-v8a

**Comment by haoxli** [comment]
I think for shared mode, need x86 and arm. I will update script.

**Comment by zqzhang** [comment]
@haoxli could you please add license info to all these packaging script files? Thanks.

Actually no need modification history info in the header.

**Comment by Honry** [comment]
I strongly suggest merge this two script into on file to reduce redundant code and maintenance effort. And if you could convert it to python would be better.

**Comment by zqzhang** [comment]
Can we merge this pull request now? @Honry

**Comment by Honry** [comment]
@haoxli will improve this script. We can hold on.

**Comment by haoxli** [comment]
@Honry  Downgrade priority to improve this script to python, you can merge this one at first.

**Comment by Honry** [comment]
OK, merge as-is.

**Pull request merged**
