### PR TITLE
Apply JSON formatter to .json files except these under wrt/

### PR DESCRIPTION
**Pull request by zqzhang**
- Add .py extensions to `json_formatter`.
- Make JSON default indent value as 2 spaces following Google JSON style guide.
- Apply JSON formatter to .json files except these under wrt/ because there are tests against manifest. I leave that to @Honry

### CODE REVIEW

**Comment by zqzhang** [comment]
@yugang PTAL, thanks.

@kangxu there are 2 fails when apply the formatting to `misc\', please check that.

@haoxli there is a fail when apply to `usecase\`, please check it.

@qiuzhong @jennycao I think this shall have no impact on test suite packaging. If any issues, please let me know.

**Comment by yugang** [comment]
i am ok with it

**Comment by wanghongjuan** [comment]
@zqzhang I have updated the all json files in wrt, the pr link https://github.com/crosswalk-project/crosswalk-test-suite/pull/2850, please review it.

**Comment by wanghongjuan** [comment]
@zqzhang  I have updated the all .json files in demo-express, the pr link https://github.com/crosswalk-project/demo-express/pull/103, please review it.

**Pull request merged**
