### PR TITLE
[pack-script] Split the pack_ios.py to 2 parts

### PR DESCRIPTION
**Pull request by qiuzhong**
Split the pack_ios.py to pack.py and build_ios.py.

BUG=https://crosswalk-project.org/jira/browse/XWALK-5040

### CODE REVIEW

**Comment by qiuzhong** [comment]
@jennycao 
For XWALK-5040, there are 3 related PRs, 
https://github.com/crosswalk-project/crosswalk-test-suite/pull/3166
https://github.com/crosswalk-project/crosswalk-test-suite/pull/3185
and this one. 

Please review so can close XWALK-5040.

**Comment by Honry** [comment]
LGTM

**Comment by Honry** [comment]
@qiuzhong, please fix the conflict.

**Comment by qiuzhong** [comment]
@jennycao , @Honry conflicts fixed.

**Pull request merged**
