### PR TITLE
[webapi] Remove idl harness test for Web Audio

### PR DESCRIPTION
**Pull request by kangxu**
BUG=https://crosswalk-project.org/jira/browse/XWALK-4506

### CODE REVIEW

**Comment by zqzhang** [comment]
Please also remove corresponding `idlharness.js`  `WebIDLParser.js` files.

**Comment by kangxu** [comment]
@zqzhang  I have updated it following your comments.

**Comment by kangxu** [comment]
@zqzhang  I have removed idlharness.js based tests and scripts

**Comment by zqzhang** [comment]
Many thanks for the quick fixing.

**Pull request merged**
