### PR TITLE
[wrt][xwalk-3590] Update script codes' installed app path

### PR DESCRIPTION
**Pull request by YongseopKim**
- Update the installed app path from 'xwalk-service' to 'xwalk'

Impacted tests(approved): new 0, update 3, delete 0
Unit test platform: [Tizen]
Unit test result summary: pass 3, fail 0, block 0

### CODE REVIEW

**Comment by ibelem** [comment]
@YongseopKim, thank you very much for the updates!

@yinhaichao Please double check if other test cases have the same issue.

**Comment by ibelem** [comment]
@YongseopKim The latest path is still /home/$TIZEN_USER/apps_rw/xwalk-service on Tizen Common (tizen-common_20150127.1_common-wayland-mbr-x86_64), what's the target of /home/$TIZEN_USER/apps_rw/xwalk change?

**Comment by WonyoungChoi** [comment]
@ibelem I think this commit should be merged after crosswalk-12. Currently tizen image is using crosswalk-11. App path was changed in https://github.com/crosswalk-project/crosswalk/commit/e4f3799ac3606fad56a5910f3b3268e9daf071af

**Comment by ibelem** [comment]
@WonyoungChoi Thank you! 

The PR https://github.com/crosswalk-project/crosswalk/pull/2717 was landed on Crosswalk 12.40.280.0.

The Crosswalk version is 11.40.277.0 on latest tizen-common_20150127.1_common-wayland-mbr-x86_64.

@yinhaichao, @jennycao said that we will test upstream Crosswalk (install the latest Canary builds from download.01.org) on Tizen common in the future, so we can merge the test cases.

@yinhaichao Please double check if other test cases have the same issue.

**Comment by ibelem** [comment]
LGTM

**Pull request merged**
