### PR TITLE
[tools] Enable Service Workers test suite in testing

### PR DESCRIPTION
**Pull request by zqzhang**

### CODE REVIEW

**Comment by zqzhang** [comment]
@chunywang @qiuzhong @Honry @yugang

**Comment by Honry** [comment]
LGTM

**Comment by zqzhang** [comment]
@ibelem @jennycao please check if this is OK to you, thanks.

**Comment by kaixinjxq** [comment]
The pull request is blocked by https://crosswalk-project.org/jira/browse/XWALK-6015. The bug is in progress.

**Pull request merged**
