### PR TITLE
[ATIP] Modify atip android gps operation step

### PR DESCRIPTION
**Pull request by jacky-young**
-Modify atip android gps operation step
-Verifid locally on related device

BUG=https://crosswalk-project.org/jira/browse/XWALK-5027

### CODE REVIEW

**Comment by jacky-young** [comment]
test on related device Nexus4, 5, 7 and zte.
@Honry please help to review it

**Comment by Honry** [comment]
Did you verify the relevant tests in WebAPI about GPS?

**Comment by jacky-young** [comment]
@Honry pr has been verified in the relevant tests in WebAPI, please merge.

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
