### PR TITLE
[release-script]Update build_ios.py for pack.py iOS backend

### PR DESCRIPTION
**Pull request by qiuzhong**
Update the build_ios.py to build ipa files for iOS deivces via
crosswalk-app as crosswalk-pkg for iOS is not supported.

Verified the ipa files can be built successfully.

BUG=https://crosswalk-project.org/jira/browse/CTS-612

### CODE REVIEW

**Comment by qiuzhong** [comment]
@Horny

**Comment by qiuzhong** [comment]
@Honry

**Comment by Honry** [comment]
@haoyunfeix, PTAL.

**Comment by haoyunfeix** [comment]
lgtm

**Pull request merged**
