### PR TITLE
[usecase][xwalk-3355] Add show and hide test for WRT

### PR DESCRIPTION
**Pull request by yinhaichao**
Impacted tests(designed): new 1, update 0, delete 0
Unit test platform: [tizen]
Unit test result summary: pass 0, fail 0, block 1

Block reason:feature triaged
https://crosswalk-project.org/jira/browse/XWALK-3341

### CODE REVIEW

**Comment by ibelem** [comment]
@yinhaichao What's the result of step 4? I suggest to remove step 4 directly.

**Comment by yinhaichao** [comment]
@ibelem Your suggestion is right, uninstall operate is not the point of this test and that it had been covered by other test. 
I will remove step 4 directly. 
Thanks for the advice.

**Comment by ibelem** [comment]
LGTM

**Comment by ibelem** [comment]
Let's wait the bug status then update it to 'approved'

**Pull request merged**
