### PR TITLE
[webapi] Remove tests on HTMLMediaElement.controller for Video

### PR DESCRIPTION
**Pull request by kangxu**
As per https://w3c.github.io/test-results/html/complete-fails.html, no browser supports the HTMLMediaElement.controller attribute and MediaController interface well. So remove corresponding test cases, and add them back if upstream Chromium and Crosswalk support them.

Bakup in https://github.com/crosswalk-project/crosswalk-test-suite/tree/designed/webapi/tct-video-html5-tests

BUG=https://crosswalk-project.org/jira/browse/XWALK-1832

### CODE REVIEW

**Comment by zqzhang** [comment]
> Remove tests on HTMLMediaElement.controller
> 
> Bakup in https://github.com/crosswalk-project/crosswalk-test-suite/tree/designed/webapi/tct-video-html5-tests

Address why make this. See https://crosswalk-project.org/jira/browse/XWALK-1832?focusedCommentId=36181&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-36181

**Comment by zqzhang** [comment]
> https://crosswalk-project.org/jira/browse/XWALK-1832

Add `BUG=`.

**Comment by kangxu** [comment]
@zqzhang  I have updated it following your comments

**Comment by zqzhang** [comment]
Thanks, please also apply to crosswalk 15 branch.

**Pull request merged**
