### PR TITLE
[webapi] Update webrtc tests

### PR DESCRIPTION
**Pull request by chunywang**
Impacted tests(approved): new 0, update 4, delete 0
Unit test platform: Crosswalk Project for Android 19.49.514.0
Unit test result summary: pass 4, fail 0, block 0

BUG= https://crosswalk-project.org/jira/browse/CTS-645

### CODE REVIEW

**Comment by Honry** [comment]
Why you do this update? Any bug/task? Or spec change?

**Comment by chunywang** [comment]
No bug/task, it's case error.

**Comment by Honry** [comment]
Pls. provide some more info about the reason.

**Comment by Honry** [comment]
LGTM

**Pull request merged**
