### PR TITLE
[usecase] Add usecase for WebCL

### PR DESCRIPTION
**Pull request by JianfengXu**
- Due to the upstream of the case have license restrictions, so rewrite usecase using external link.
- Fail Reason: the ZTE devices do not support WebCL.

Impacted TCs num(approved): New 1, Update 0, Delete 0
Unit test Platform: Andriod
Unit test result summary: Pass 0, Fail 1, Blocked 0

### CODE REVIEW

**Comment by JianfengXu** [comment]
Please do not pay attention to this PR for the moment, I need to verify this usecase in memo device first.

**Comment by zqzhang** [comment]
Any update since you have gotten a MeMO pad?

**Comment by JianfengXu** [comment]
@zqzhang I have run this sample on MEMO Pad, the test result is fail. This external link is base on Nokia WebCL for Firefox, maybe not suitable for our platform . I think we need find another link to replace it.

**Comment by zqzhang** [comment]
Seems so.

**Pull request closed without merging**
