### PR TITLE
[tools]Add pack_deb.py file for linux

### PR DESCRIPTION
**Pull request by yinhaichao**
Impacted tests(approved): new 1, update 0, delete 0
Unit test platform: [Linux]
Unit test result summary: pass 1, fail 0, block 0

### CODE REVIEW

**Comment by ibelem** [comment]
@jennycao Could you please help to check if we need a separate pack_linux.py or merge the pack_linux.py into pack.py?

**Comment by jennycao** [comment]
suggest to keep seperate files, we could merge if there is more request.
another suggestion, it would be better pack_deb.py ? since pack.py also executed on linux , right ?

**Comment by ibelem** [comment]
Thanks @jennycao  for the suggestions! @yinhaichao please update the file name. :)

**Comment by ibelem** [comment]
LGTM

**Pull request merged**
