### PR TITLE
[apptools] Add missing "apkLength" variable initialization in funtion

### PR DESCRIPTION
**Pull request by haoyunfeix**
For fixing CI failure on appVeyor.

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@Honry PHAL

**Comment by Honry** [comment]
Thanks, pls. provide the UT result.

**Comment by haoyunfeix** [comment]
UT test result added, all passed on appveyor CI

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
