### PR TITLE
[usecase-apptools] Update contactextension.jar for android apptools usecase

### PR DESCRIPTION
**Pull request by yunxliu**
Impacted tests(approved): new 0, update 1, delete 0
Unit test platform: [Android]
Unit test result summary: pass 1, fail 0, block 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-6508

### CODE REVIEW

**Comment by Honry** [comment]
What's the reason for this update?

**Comment by yunxliu** [comment]
Due to the source of contactextension has been changed, so need to rebuilt the JAR file.

**Comment by Honry** [comment]
Please also file a task to track the effort.

**Comment by Honry** [comment]
LGTM

**Pull request merged**
