### PR TITLE
[EmbeddingAPI] Reorganize the usecase UI & java file name

### PR DESCRIPTION
**Pull request by jacky-young**
-Reorganize the usecase UI
-Modify java file name
-Modify layout xml content

Impacted tests(approved): new 0, update 60, delete 0
Unit test platform: [Android]
Unit test result summary: pass 60, fail 0, block 0

https://crosswalk-project.org/jira/browse/XWALK-5056

### CODE REVIEW

**Comment by jacky-young** [comment]
@Shao-Feng embeddingapi usecase reorganization step2 has finished. please help to review.

**Comment by Shao-Feng** [comment]
should not simply remove the attribute “parentactivity"

**Comment by jacky-young** [comment]
@Shao-Feng Please review again.

**Comment by Shao-Feng** [comment]
LGTM

**Pull request merged**
