### PR TITLE
[webapi] Update 3 manual cases to auto cases for extra

### PR DESCRIPTION
**Pull request by yunxliu**
- Add 3 reference files

Impacted tests(approved): new 0, update 3, delete 0
Unit test platform: [Android]
Unit test result summary: pass 3, fail 0, block 0

### CODE REVIEW

**Comment by zqzhang** [comment]
Please submit to W3C and integrate back after they have been accepted.No `extra`, no `3` in commit message.

**Comment by yunxliu** [comment]
These manual cases don't come from W3C, so don't need to submit reference files to W3C.

**Comment by zqzhang** [comment]
Are these tests qualified to be submitted to W3C?

**Comment by yunxliu** [comment]
The 3 tests are not suitable to do reference test, so close this pr.

**Pull request closed without merging**
