### PR TITLE
[usecase-wrt] Remove usecase-wrt-auto-tests due to make_apk.py deprecated

### PR DESCRIPTION
**Pull request by haoxli**
- This suite check make_apk.py:<br/>
   build location<br/>
   --project-dir<br/>
   --compressor<br/>
   --app-version<br/>

https://crosswalk-project.org/jira/browse/XWALK-6148

### CODE REVIEW

**Comment by haoxli** [comment]
@wanghongjuan please help to review this PR, thanks.

**Comment by Honry** [comment]
Are all the tests in this suite for make_apk command line testing?

**Comment by chunywang** [comment]
Yes. They are for "--project-dir", "--compressor", "--app-version" options in make_apk.py, these are not supported in app tools.

**Comment by haoxli** [comment]
Yes. They are for "--project-dir", "--compressor", "--app-version" options in make_apk.py, these are not supported in app tools.

**Comment by Honry** [comment]
LGTM

**Comment by Honry** [comment]
Please also remove it from tools/build/released_suites/PLATFORMS

**Comment by Honry** [comment]
LGTM

**Pull request merged**
