### PR TITLE
[webapi] Remove audio and video block tests

### PR DESCRIPTION
**Pull request by JianfengXu**
- These tests is bloked because of some events failed to invoke, and these check points are not good for w3c, so remove thest tests.
- Related PR:https://github.com/crosswalk-project/crosswalk-test-suite/pull/1993

Impacted TCs num(approved): New 0, Update 0, Delete 7
Unit test Platform: Crosswalk Project for Android 15.43.347
Unit test result summary: Pass 0, Fail 0, Blocked 0

BUG=https://crosswalk-project.org/jira/browse/XWALK-3646

### CODE REVIEW

**Comment by zqzhang** [comment]
You are trying to remove all tests against wav PCM audio clip. Does it mean the platform doesn't support that audio format? If yes, that is strange.

**Comment by JianfengXu** [comment]
The issue has been discussed in #1993. This PR is just integrate https://github.com/crosswalk-project/crosswalk-test-suite/pull/1993 to Crosswalk-13 branch.
If change the execution type to manual, these cases can be pass.

**Comment by JianfengXu** [comment]
The issue has been discussed in #1993. This PR is just integrate https://github.com/crosswalk-project/crosswalk-test-suite/pull/1993 to Crosswalk-13 branch.
If change the execution type to manual, these cases can be pass.

**Comment by JianfengXu** [comment]
The issue has been discussed in #1993. This PR is just integrate https://github.com/crosswalk-project/crosswalk-test-suite/pull/1993 to Crosswalk-13 branch.
If change the execution type to manual, these cases can be pass.

**Comment by JianfengXu** [comment]
The issue has been discussed in #1993. This PR is just integrate https://github.com/crosswalk-project/crosswalk-test-suite/pull/1993 to Crosswalk-13 branch.
If change the execution type to manual, these cases can be pass.

**Pull request merged**
