### PR TITLE
[webapi][XWALK-3646] Remove audio and video blok tests

### PR DESCRIPTION
**Pull request by xinliux**
These tests is bloked because of some events failed to invoke, and these check points are not good for w3c,  so remove thest tests.

### CODE REVIEW

**Comment by zqzhang** [comment]
Seems you still not fix the issue.

**Comment by zqzhang** [comment]
Hmm, I prefer removing these tests if they are not qualified to submit to W3C.

**Comment by zqzhang** [comment]
Ping @xinliux

**Comment by xinliux** [comment]
I will remove these cases as soon as possible.

**Pull request merged**
