### PR TITLE
[misc]Delete the discarded suite.

### PR DESCRIPTION
**Pull request by jiajiax**

### CODE REVIEW

**Comment by jiajiax** [comment]
@haoyunfeix This suites can be deleted now,right?

**Comment by Honry** [comment]
+ @jennycao

**Comment by haoyunfeix** [comment]
Yes, please.

**Comment by haoyunfeix** [comment]
Yes, please.

**Comment by jiajiax** [comment]
@Honry @jennycao This suties is discarded , delete it.

**Comment by Honry** [comment]
OK for me, @jennycao

**Comment by jennycao** [comment]
ok for me

**Pull request merged**
