### PR TITLE
[usecase] Automate 1 usecase

### PR DESCRIPTION
**Pull request by JianfengXu**
This PR is dependent on PR#1960

Impacted TCs num(approved): New 0, Update 1, Delete 0
Unit test Platform: Andriod
Unit test result summary: Pass 1, Fail 0, Blocked 0

### CODE REVIEW

**Comment by Honry** [comment]
Please note the dependency of this PR.

**Comment by Honry** [comment]
One more, the subcase num in tests.auto.xml also needs update.

**Comment by Honry** [comment]
Per PR#1960 has been refined and merged, please based on the latest code and redo the unit test.

**Comment by JianfengXu** [comment]
@Honry I have tested the case base on the latest code, test result is PASS.

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
