### PR TITLE
[apptools] Centralize scripts of web runner and test xsl

### PR DESCRIPTION
**Pull request by kangxu**
- Update suite.json to centralize scripts of web runner and test xsl

### CODE REVIEW

**Comment by zqzhang** [comment]
@Honry

**Comment by Honry** [comment]
Thanks, @kangxu, and please help provide the UT result. Only need to try if test suite can be built successfully and tests run normally.

**Comment by kangxu** [comment]
@Honry  Test suite can be built successfully and tests run normally

**Comment by Honry** [comment]
Thanks, LGTM

**Pull request merged**
